### ISSUE TITLE
About some function in Fastspeech 2

### ISSUE THREAD

**Issue by JoeyHeisenberg** [TensorSpeech/TensorFlowTTS#160]
maybe some value minus the average value will go to zero, it means the value zero stand for two things? and it seems the value next to zero loss the meaning that is next to the average value?

![image](https://user-images.githubusercontent.com/33407667/88611419-8a8a4280-d0bb-11ea-8239-61bca7439e77.png)
![image](https://user-images.githubusercontent.com/33407667/88611450-9bd34f00-d0bb-11ea-950b-89b86f7c9889.png)

**Comment by dathudeptrai** [comment]
@JoeyHeisenberg you are right about the problem with this function is that the model hard to classify the unvoice part and the voice part that its f0 nearby mean value. I also tested a model remove the code above but the quality is the same, I think the network is already large enough to solve this problem. I will commit the change to be sure this problem is not affected in other dataset. 

cc: @candlewill , I think you have an idea to solve this problem. :)))
