### ISSUE TITLE
🇰🇷 Korean TTS now available 😘

### ISSUE THREAD

**Issue by dathudeptrai** [TensorSpeech/TensorFlowTTS#183]
Korean TTS now available, thank Jaehyoung Kim (@crux153) for his support :D. The model used KSS dataset here (https://www.kaggle.com/bryanpark/korean-single-speaker-speech-dataset). Thank @Kyubyong for the opensource korea dataset :D. The pretrained model licensed under `CC BY-NC-SA 4.0` (https://creativecommons.org/licenses/by-nc-sa/4.0/) as same as the license of original KSS dataset.

Pls check out the colab bellow and enjoy :D.

https://colab.research.google.com/drive/1ybWwOS5tipgPFttNulp77P6DAB5MtiuN?usp=sharing

**Comment by Joovvhan** [comment]
Thanks, I will try that and update my review page.

BTW, I applied [G2PK](https://github.com/Kyubyong/g2pK), Korean grapheme to phoneme conversion package, and improved the quality of the GlowTTS.

[GlowTTS without G2PK](https://joovvhan.github.io/glow-tts-demo-korean-mb-melgan/)
[GlowTTS with G2PK](https://joovvhan.github.io/glow-tts-demo-korean-mb-melgan-g2pk/)

Did your FS2 also use such a module to convert grapheme to phoneme?

I wonder FS2 can also be improved using the G2PK module.

**Comment by dathudeptrai** [comment]
> Thanks, I will try that and update my demo page.
> 
> BTW, I applied [G2PK](https://github.com/Kyubyong/g2pK), Korean grapheme to phoneme conversion package, and improved the quality of the GlowTTS.
> 
> [GlowTTS without G2PK](https://joovvhan.github.io/glow-tts-demo-korean-mb-melgan/)
> [GlowTTS with G2PK](https://joovvhan.github.io/glow-tts-demo-korean-mb-melgan-g2pk/)
> 
> Did your FS2 also use such a module to convert grapheme to phoneme?
> 
> I wonder FS2 can also be improved using the G2PK module.

Thank you for ur infomation. I do not know the korean language so i can't support more :D. The korean model here is supported by @crux153 :))). I appreciate if someone can make a pull request to improve a base model :D

**Comment by Joovvhan** [comment]
> > Thanks, I will try that and update my demo page.
> > BTW, I applied [G2PK](https://github.com/Kyubyong/g2pK), Korean grapheme to phoneme conversion package, and improved the quality of the GlowTTS.
> > [GlowTTS without G2PK](https://joovvhan.github.io/glow-tts-demo-korean-mb-melgan/)
> > [GlowTTS with G2PK](https://joovvhan.github.io/glow-tts-demo-korean-mb-melgan-g2pk/)
> > Did your FS2 also use such a module to convert grapheme to phoneme?
> > I wonder FS2 can also be improved using the G2PK module.
> 
> Thank you for ur infomation. I can't understand the korean language so i can't support more :D. The korean model here is supported by @crux153 :))). I appreciate if someone can make a pull request to improve a base model :D

Thanks for the quick reply.

I will look through your source code and ask @crux153 by myself.

Thanks!

**Comment by crux153** [comment]
@Joovvhan It won't take too long to apply [G2PK](https://github.com/Kyubyong/g2pK) or other Korean G2P module to this package. Actually I also thought about applying it, but since I'm using the trained model in C++ and that requires porting the G2P module itself to C++, which might take a while.

I'm satisfied with current quality of FS2 model except that it fails to synthesize long samples, and I'm trying to fix in #208. Maybe training using phoneme might help fixing this.

https://github.com/HGU-DLLAB/Korean-FastSpeech2-Pytorch

I found another FS2 implementation for Korean. Take a look if you haven't. It is trained with KSS using phoneme, and uses MFA to extract durations (instead of Tacotron2). Audio samples are glitchy, but I think WaveGlow vocoder is responsible for this, not FS2 itself. Downloading the trained model and feeding our MB-MelGAN model with mels from it will verify this, but I didn't have much time to do so :(

Please share your progress if you've got any :D

**Comment by ZDisket** [comment]
@crux153 
> but since I'm using the trained model in C++ and that requires porting the G2P module itself to C++, which might take a while.

Perhaps you should consider Phonetisaurus, which the current C++ example here already uses for G2P. It's even compatible with pretrained G2P models in Montreal Forced Aligner's page (just did for Spanish).
