### ISSUE TITLE
my training audio sampling rate is 16k，how to change  **_preprocess.yaml

### ISSUE THREAD

**Issue by peter05010402** [TensorSpeech/TensorFlowTTS#278]
Hi,

my training audio sampling rate is 16k，how to change  **_preprocess.yaml

Thank you!!!

**Comment by ZDisket** [comment]
@peter05010402 You change the `hop_size `to a number that equals your `num_mels `(by default 80) when you divide the sampling rate by it. For example, I just [changed ](https://github.com/ZDisket/TensorflowTTS/blob/multi-emt/preprocess/ljspeechv3_32k_preprocess.yaml)a config for a 32KHz mb-melgan with `hop_size `400 because 32000 / 400 = 80
You also have to set the `hop_size `in the training configs and if you're training a vocoder, change the `upsample_scales`.

**Comment by peter05010402** [comment]
@ZDisket Thank your reply ：）
