### ISSUE TITLE
Windows doesnt recognize TTS

### ISSUE THREAD

**Issue by luis-vera** [TensorSpeech/TensorFlowTTS#374]
Hi.  I installed TensorflowTTS and when I tried to execute tensorflow-tts-preprocess, I found this error message:

tensorflow-tts-preprocess --rootdir ../ljspeech --outdir dump_ljspeech --config preprocess/ljspeech_preprocess.yaml --dataset ljspeech
"tensorflow-tts-preprocess" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

I don't know why this command is not known by Windows 10.

**Comment by OscarVanL** [comment]
This is because you have to do `pip install .` in the TensorFlowTTS folder to register these endpoints :)

Specifically, these endpoints are defined in:

https://github.com/TensorSpeech/TensorFlowTTS/blob/d1789e301215205745c9a7036cb37bd4dda76c20/setup.py#L54-L61

Just beware, if you install the TensorFlowTTS directory it will copy anything within the folder to your Python Environment (so don't have any big datasets within the TensorFlowTTS directory.)

**Comment by luis-vera** [comment]
Hi OscarVanL  I tried it in another machine and it worked. I am new in this area and I will train the dataset with tacotron.

Thanks a lot
