### ISSUE TITLE
Trying to run mfa for Korean Fastspeech2, does anyone know where I can find Korean lexicon?

### ISSUE THREAD

**Issue by charlie-codes-choi** [TensorSpeech/TensorFlowTTS#385]
EoM

**Comment by ZDisket** [comment]
@charlie-codes-choi You can find a pretrained acoustic and G2P Korean model here: https://montreal-forced-aligner.readthedocs.io/en/latest/pretrained_models.html
Since there are no dictionaries, you'll have to generate one. The documentation shows how to: https://montreal-forced-aligner.readthedocs.io/en/latest/g2p_dictionary_generating.html

**Comment by charlie-codes-choi** [comment]
Fantastic. Thanks a lot ZDisket! I will try it and share how it went here.

**Comment by Jackson-Kang** [comment]
Hello, @ZDisket and @charlie-codes-choi .

The pretrained Korean MFA model has an issue. Please see the below.
https://github.com/HGU-DLLAB/Korean-FastSpeech2-Pytorch/issues/3#issuecomment-731979268

I recommend to generate dictionary for your own dataset using g2pk module (https://github.com/Kyubyong/g2pK).
