### ISSUE TITLE
TenosrflowTTS and german_transliterate licences are not compatible

### ISSUE THREAD

**Issue by machineko** [TensorSpeech/TensorFlowTTS#454]
https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licences

**Comment by monatis** [comment]
Hi @machineko This was my mistake unfortunately, sorry for that.
I'll reach out to the author of german_transliterate immediately and ask if there is a possibility to re-license it with a compatible license. Otherwise, I'll introduce my own implementation with Apache 2.0. Thanks a lot for raising this issue.

**Comment by machineko** [comment]
@monatis
