### ISSUE TITLE
Is Fastspeech2 really better than Fastspeech1？

### ISSUE THREAD

**Issue by Liujingxiu23** [TensorSpeech/TensorFlowTTS#550]
I trained Fastspeech2 using my own dataset usig code https://github.com/ming024/FastSpeech2 
but the result is not good enough, seems even worse than fastspeech1. 
What about your training?

**Comment by dathudeptrai** [comment]
@Liujingxiu23 you can listen a samples here (https://tensorspeech.github.io/TensorFlowTTS/). FS2 is definitely better than FS1.

**Comment by Liujingxiu23** [comment]
@dathudeptrai  Thank you for your quick reply. I find differences between https://github.com/ming024/FastSpeech2 and fastspeech in tensorflowTTS.
And I am tring to train my own Chinese dataset using TensorflowTTS.
But I meet following mistacks:

tensorflow.python.framework.errors_impl.InvalidArgumentError: All elements in a batch must have the same rank as the padded shape for component7: expected rank 0 but got element with rank 1
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]]

I revise "examples/fastspeech2/fastspeech2_dataset.py" to add speaker_id and prosody feature in chinese.

padded_shapes = {
    "utt_ids": [],
    "speaker_ids": [],
    "phone_ids": [None],
    "prosody_ids": [None],
    "duration_gts": [None],
    "f0_gts": [None],
    "energy_gts": [None],
    "mel_gts": [None, None],
    "mel_lengths": [],
}

Could you help me finger out the problem?

**Comment by ZDisket** [comment]
@Liujingxiu23 I haven't tried FastSpeech1 but FastSpeech2 definitely yields very good performance for me. You can listen to [my samples](https://soundcloud.com/zyklone2/sets/tucker-carlson-441khz-tensorflowttsmb-melgan). I freely distribute most of my models to be used with [my program](https://github.com/ZDisket/TensorVox), if you want to test it.

One thing to note is that it's way more resilient against bad datasets (like those with noise or transcripts from speech-to-text services instead of humans) than Tacotron 2.

**Comment by Liujingxiu23** [comment]
@ZDisket Thank you very much for your reply. 
I trained using https://github.com/ming024/FastSpeech2 , and the generated wavs is clear but the pitch seems a lot strange, I do not know whether this phenomenon is common and normal.
But I decided to using TensorflowTTS to train Fastspeech2 again since there are more discussions here which may help me a lot.
I am working on process dataset now. Is it a litte time-comsuming since each code has its own data format.
