### ISSUE TITLE
prosody problem for fastspeech2 with phoneme durations extracted by MFA

### ISSUE THREAD

**Issue by jarred1989** [TensorSpeech/TensorFlowTTS#552]
With durations extracted by MFA, we take phoneme and 'sil' as input of fastspeech2. However, with this approach, the model cannot distinguish "weekend" from "week end",  "sunrise" from "sun rise",  .etc, because these word pairs have the same phoneme representations. 

In other words, we lose syllable and word boundary infomations with only phoneme and 'sil' input, which cause prosody problem. The synthesized audio sounded not naturally as ground true  even with manual adjustment of 'sil' input for me. 

In my opinion, we should insert symbols such as '#0' to represent boundary in phoneme inputs both in training and evaluation.  But I am not sure how to implement it? set the duration of '#0' to 0 or other better approaches? 

It is a more complex problem for Chinese language, which typically use #1 #2 #3 as prosody symbols.  How should we merge them into phoneme sequence properly? and is 'sil' still needed? they all more or less be represented as pause.

Do you guys have any ideas?

**Comment by luan78zaoha** [comment]
In training data, a word boundary could be added between each word, like "#0", the punctuation can be replaced by a symbol of "# 3", and "sil" is only placed at the beginning and end of the sentence. The model will be trained based on phoneme, "sil", "#0" and "# 3". When inferencing, the words "weekend" and "week #0 end" can be distinguished by adding #0.

**Comment by jarred1989** [comment]
@luan78zaoha  Thank you for your reply, but with 'sil' only at beginning and end, what to do with duration related to 'sil' in the middle of sentence（MFA align result may add 'sil' symbols and corresponding durations）?  And do we need to set duration of '#0' to 0?

**Comment by luan78zaoha** [comment]
@jarred1989
- Because the beginning or end of audio file (.wav or .mp3) usually have a long silence, one symbol like “sil_0” could be used to indicate this kind of silence. In the middle of sentence, you can define different silence symbols according to durations of "sil" and "sp" from MFA. For example, the silence duration less 150ms is marked as "sil_1", the silence duration less 300ms is marked as "sil_2", and the others are all marked as "sil_3".  In addition, you could remove the symbols less 50ms.
- The duration of '#0' is needed to set to zero. I have tried, that's no problem. Also, you can try to set duration to 1 or 2 (frame), it may have a better result.

**Comment by jarred1989** [comment]
@luan78zaoha Thanks again for your advice. I will try it soon, hope for good result.
