### ISSUE TITLE
Hope to support new algorithm :Parallel Tacotron 2: A Non-Autoregressive Neural TTS Model with Differentiable Duration Modeling

### ISSUE THREAD

**Issue by qxde01** [TensorSpeech/TensorFlowTTS#562]
[paper](https://arxiv.org/pdf/2103.14574.pdf)  :
Parallel Tacotron 2: A Non-Autoregressive Neural TTS Model with Differentiable Duration Modeling

![image](https://user-images.githubusercontent.com/2479536/118064298-50312e00-b3cd-11eb-84d7-850a4170004c.png)

**Comment by dathudeptrai** [comment]
@qxde01 I have read a paper :))), right now I can say that: It's very hard to implement this model in TensorFlow even with PyTorch and we need few months to reproduce its performance :)).

**Comment by qxde01** [comment]
@dathudeptrai ,yes,thank you. I find two unofficial pytorch code:
[https://github.com/keonlee9420/Parallel-Tacotron2](https://github.com/keonlee9420/Parallel-Tacotron2)
[https://github.com/NTT123/Parallel-Tacotron-2](https://github.com/NTT123/Parallel-Tacotron-2)

**Comment by dathudeptrai** [comment]
> @dathudeptrai ,yes,thank you. I find two unofficial pytorch code:
> https://github.com/keonlee9420/Parallel-Tacotron2
> https://github.com/NTT123/Parallel-Tacotron-2

yeah, I know it. Let us see how long will the community take to make that model convergence :)).

**Comment by keonlee9420** [comment]
Hi @qxde01 and @dathudeptrai , thank you for mentioning my work.
As you may know, it's a bit hard to reproduce (mainly due to ambiguous descriptions in the paper). I've contacted the original authors, and they gave me some hints. Based on it, I'm currently debugging and tuning the model to converge. It would be boosted a lot if you can contribute as a speech domain expert. I genuinely believe in collective intelligence:)
