### ISSUE TITLE
Control speech duration

### ISSUE THREAD

**Issue by tuliomagalhaes** [TensorSpeech/TensorFlowTTS#586]
I am developing a TTS system that the synthetized audio duration should match a given duration.
I was looking in the issues and I found this one #489 but I'm not sure how I can manipulate this array to match my duration because I don't know exactly the scale of this values, if is in seconds, miliseconds, etc.

**Comment by dathudeptrai** [comment]
@ZDisket

**Comment by ZDisket** [comment]
@tuliomagalhaes 
The scale of the duration outputs is in mel spectrogram frames, you can verify this because `np.sum(duration_outputs)` will always equal the amount of spectrogram frames (`mel_outputs.shape[1]`) when you generate. To convert them to seconds, you use the formula `seconds = mel frames / (sampling rate / hop size)` 
In order to manipulate the speed multiplier I would suggest first generating it with default argument for the speed (`speed_ratios=[1.0]`), then converting to seconds, using math to find out what multiplier you'd need to match your desired duration, then generating again with this multiplier as your new speed_ratios

**Comment by tuliopereirazup** [comment]
Thanks for you response, I will try that. =)

**Comment by tuliomagalhaes** [comment]
Thanks for you response, I will try that.

But when you say to create a custom inference function is to make all this calculation inside the DurationPredictor? Or in fact change how the prediction is done and try to predict the exactly given duration?

**Comment by PedroDKE** [comment]
if I'm right you can just use the durations you want (in the right format) as input to the length regulator [here](https://github.com/TensorSpeech/TensorFlowTTS/blob/fbb0655e0ec7403e442baf7d2ce7c3ed1aa4cfed/tensorflow_tts/models/fastspeech2.py#L265). This will change the duration of each grapheme/phoneme to the given one instead of the predicted one during inference

**Comment by samuel-lunii** [comment]
I would also recommend not to modify the duration of consonants too much, as most of the duration reduction in each syllable with faster speech is done inside the vowels, according to e.g. [[Bartkova & Sorin 1987](https://www.sciencedirect.com/science/article/abs/pii/016763938790029X), [Kuwabara 1996](http://www.asel.udel.edu/icslp/cdrom/vol4/301/a301.pdf)] :) 

Reducing consonants duration too much could reduce intelligibility.

**Comment by tuliomagalhaes** [comment]
I tried what @ZDisket said, and it worked but with one problem. The generated mel spectogram is associated with the speaker and vocoder, the duration calculated with the mel spectogram vary from the generated waveform. And what @samuel-lunii have said, make sense too.
